ignorePatterns:
  - pattern: "^http://localhost"
  - pattern: "^https://doi.org/<replace-with-created-DOI>"
  - pattern: "^https://github.com/.*/settings/secrets/actions$"
  - pattern: "^https://github.com/organizations/.*/repositories/new"
  - pattern: "^https://test.pypi.org"
  - pattern: "^https://bestpractices.coreinfrastructure.org/projects/<replace-with-created-project-identifier>"
  - pattern: "^https://readthedocs.org/dashboard/import.*"

useGitIgnore: true
