---
name: pystemmusscope_3.8
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8 # supported by matlab R2021a, see issue #31
  - jupyterlab # needed to run notebooks
  - pip:
      - git+https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing.git@main # will be replaced by `pip install pystemmusscope`
